### ISSUE TITLE
Overengineering

### ISSUE THREAD

**Issue by LordFokas** [LordFokas/SiLo#1]
The whole caching mechanism thing is just too much, and it feels little clutter amongst what really matters.
If anyone really ever needs to locally cache language objects they can very well do it themselves.

**Tasks:**
- [x] Remove the caching function and object from the code
- [x] Remove the caching example from the /examples dir
- [x] Remove the caching references from Readme.md
