### ISSUE TITLE
Language key

### ISSUE THREAD

**Issue by LordFokas** [LordFokas/SiLo#2]
Right now SiLo looks for `data-silo-key` attributes in elements with something along the lines of `element.dataset.siloKey`, which we call the `language key`.

However, the hardcoded `siloKey` value is quite ugly and users deserve the chance to use whatever key they want (making it seem fit the code and not conflict with any other attributes).

**Tasks:**
- [x] Use a string variable to determine the language key to use. Default value should still be `"siloKey"`.
- [x] Implement a function with signature `language_key( key )`. Put it in the right place on the code and map it out on the returned object accordingly (use your head :) ).
- [x] Update the right part of the documentation (Readme.md) to reflect the changes.
