### ISSUE TITLE
Direct localize

### ISSUE THREAD

**Issue by LordFokas** [LordFokas/SiLo#3]
An option to look up the localization of a dictionary key (like `foo.bar.test`, without the `func:` descriptor) directly should be available.

The localization mechanism can be seen here https://github.com/LordFokas/SiLo/blob/master/silo.js#L16-L28 (first 2 lines) and subsequent boilerplate (to ensure there is a return value).

**Tasks:**
- [x] Add a direct localization function. It should have the signature `localize_direct( key )`, and be placed and mapped out accordingly. It **must** return null when a localization is not found. It **must** call the appropriate warning callbacks and use the fallback mechanism.
- [x] The current `localize` function should now use this function to get string localizations.
- [x] Add the respective documentation to Readme.md.
